export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";
export const ALL_ROOMS_LOADING = "ALL_ROOMS_LOADING";
export const CURRENT_ROOM_SUCCESS = "FILTER_ROOMS_SUCCESS";
export const CURRENT_ROOM_FAIL = "FILTER_ROOMS_FAIL";
export const CURRENT_ROOM_LOADING = "FILTER_ROOMS_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
