export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";
export const ALL_ROOMS_LOADING = "ALL_ROOMS_LOADING";
export const FILTER_ROOMS_SUCCESS = "FILTER_ROOMS_SUCCESS";
export const FILTER_ROOMS_FAIL = "FILTER_ROOMS_FAIL";
export const FILTER_ROOMS_LOADING = "FILTER_ROOMS_LOADING";
export const CLEAR_ERROS = "CLEAR_ERRORS";
